<div class="styleguide__block" id="r<?php echo $vars['section']->getReference(); ?>">
    <h3 class="styleguide__block__header">
        <span class="styleguide__block__title"><?php echo $vars['section']->getDescriptionTitle(); ?></span>
        <span class="styleguide__block__filename"><?php echo $vars['section']->getFilename(); ?></span>
    </h3>

    <div class="styleguide__block__description">
        <p><?php echo nl2br($vars['section']->getDescriptionText()); ?></p>
        <?php
            if (count($vars['section']->getModifiers()) > 0) {
        ?>
            <ul class="styleguide__block__modifiers">
                <?php foreach ($vars['section']->getModifiers() as $modifier) { ?>
                    <li>
                        <span class="styleguide__block__modifier-name <?php echo ($modifier->isExtender()) ? 'styleguide__modifier-name--extender' : ''; ?>">
                            <?php echo $modifier->getName(); ?>
                        </span>
                            <?php if ($modifier->isExtender()) { ?>
                                @extend
                                <span class="styleguide__block__modifier-name"><?php echo $modifier->getExtendedClass(); ?></span>
                            <?php } ?>
                        <?php if ($modifier->getDescription()) { ?>
                            - <?php echo $modifier->getDescription(); ?>
                        <?php } ?>
                    </li>
                <?php } ?>
            </ul>
        <?php } ?>

        <?php
            if (count($vars['section']->getParameters()) > 0) {
        ?>
            <ul class="styleguide__block__parameters">
                <?php foreach ($vars['section']->getParameters() as $parameter) { ?>
                    <li>
                        <span class="styleguide__block__parameter-name">
                            <?php echo $parameter->getName(); ?>
                        </span>
                        <?php if ($parameter->getDescription()) { ?>
                            - <?php echo $parameter->getDescription(); ?>
                        <?php } ?>
                    </li>
                <?php } ?>
            </ul>
        <?php } ?>

        <?php
            if ($vars['section']->getCompatibility()) {
        ?>
            <p class="styleguide__block__compatibility"><?php echo nl2br($vars['section']->getCompatibility()); ?></p>
        <?php } ?>
    </div>


    <?php
        if ($vars['section']->hasMarkup()) {
    ?>

    <nav class="styleguide__block__tabs">
        <a class="styleguide__block__enlarge" href="index.php?preview&ref=<?php echo $vars['section']->getReference(); ?>&src=<?php echo $vars['styleguide']->getSource()->getKey(); ?>" target="_blank"><span class="fa fa-arrows-alt"></span></a>
        <ul class="nav nav-tabs">
            <li class="active"><a href="#styleguidePreview<?php echo str_replace(".", "_", $vars['section']->getReference() . $vars['styleguide']->getSource()->getKey()); ?>">Preview</a></li>
            <li><a href="#styleguideMarkup<?php echo str_replace(".", "_", $vars['section']->getReference() . $vars['styleguide']->getSource()->getKey()); ?>">Markup</a></li>
            <li><a href="#styleguideComments<?php echo str_replace(".", "_", $vars['section']->getReference() . $vars['styleguide']->getSource()->getKey()); ?>">Notes (ToDo)</a></li>
        </ul>
    </nav>

    <div class="tab-content styleguide__block__preview">
        <div class="tab-pane active styleguide__block__elements" id="styleguidePreview<?php echo str_replace(".", "_", $vars['section']->getReference() . $vars['styleguide']->getSource()->getKey()); ?>">
            <div class="styleguide__block__element" data-preview="frame">
                <iframe src="index.php?preview&ref=<?php echo $vars['section']->getReference(); ?>&src=<?php echo $vars['styleguide']->getSource()->getKey(); ?>"></iframe>
            </div>
            <?php /* foreach ($vars['section']->getModifiers() as $modifier) { ?>
                <div class="styleguide__block__element styleguide__element--modifier <?php ($modifier->isExtender()) ? 'styleguide__element--extender' : ''; ?>">
                    <span class="styleguide__block__element__modifier-label <?php echo ($modifier->isExtender()) ? 'styleguide__element__modifier-label--extender' : ''; ?>"><?php echo $modifier->getName(); ?></span>
                    <iframe src="index.php?preview&ref=<?php echo $vars['section']->getReference(); ?>&src=<?php echo $vars['styleguide']->getSource()->getKey(); ?>&modifier=<?php echo $modifier->getName(); ?>"></iframe>
                </div>
            <?php }  */?>
        </div>

        <div class="tab-pane styleguide__block__html" id="styleguideMarkup<?php echo str_replace(".", "_", $vars['section']->getReference() . $vars['styleguide']->getSource()->getKey()); ?>">
            <pre class="styleguide__block__code"><code class="html"><?php echo htmlentities($vars['section']->getMarkupNormal('{class}')); ?></code></pre>
        </div>
    </div>
    <?php
        }
    ?>
</div>
