<h1>Globals</h1>
<section class="styleguide__block">
<h3 class="styleguide__block__header">
        <span class="styleguide__block__title">Farben</span>
    </h3>

    <div class="styleguide__block__description">Grund- und Schmuckfarben</div>

	<div class="styleguide__colors styleguide__colors--primary">
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-primary">@brand-primary</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--gray">@gray</figure>
	</div>
	<div class="styleguide__colors">
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-success">@brand-success</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-warning">@brand-warning</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-danger">@brand-danger</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-info">@brand-info</figure>
	</div>
	<h4>Theme 1 (Gray)</h4>
	<div class="styleguide__colors">
		<figure class="styleguide__colorswatch styleguide__colorswatch--gray-darker">@gray-darker</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--gray-dark">@gray-dark</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--gray">@gray</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--gray-light">@gray-light</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--gray-lighter">@gray-lighter</figure>
	</div>
	<h4>Theme 2 (Brand Dark)</h4>
	<div class="styleguide__colors">
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-secondary-darker">@brand-secondary-darker</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-secondary-dark">@brand-secondary-dark</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-secondary">@brand-secondary</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-secondary-light">@brand-secondary-light</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-secondary-lighter">@brand-secondary-lighter</figure>
	</div>
	<h4>Theme 3 (Success)</h4>
	<div class="styleguide__colors">
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-success-darker">@brand-success-darker</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-success-dark">@brand-success-dark</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-success">@brand-success</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-success-light">@brand-success-light</figure>
		<figure class="styleguide__colorswatch styleguide__colorswatch--brand-success-lighter">@brand-success-lighter</figure>
	</div>


</section>

<section class="styleguide__block">
	<h3 class="styleguide__block__header">
        <span class="styleguide__block__title">Font-Stacks</span>
    </h3>

    <!-- <div class="styleguide__description"></div> -->
    <h1>Lato Black: Header Level 1</h1>
    <h2>BenchNine: Subheader</h2>

    <p>Lato Light: Fließtext</p>

    <p class="decorative">Dancing Script als Dekoration</p>

</section>

<section class="styleguide">
	<h3 class="styleguide__header">
        <span class="styleguide__title">Example Copy</span>
    </h3>

    <header class="heading">
    	<span class="decorative">Looking down on the atmosphere...</span>
		<h1>Lorem Ipsum dolor</h1>
		<p class="heading__subheader">the quick brown fox</p>
    </header>

    <p class="lead">You need to sit down and sketch more fucking ideas because stalking your ex on facebook isn’t going to get you anywhere.</p>
    <p>Someday is not a fucking day of the week. Respect your fucking craft. Use your fucking hands. Must-do is a good fucking master. Design as if your fucking life depended on it. </p>
    <h2>Jumps over the lazy dog</h2>
    <p>Must-do is a good fucking master. Design as if your fucking life depended on it. Can we all just agree as the greater design community to stop fucking talking about Comic Sans altogether? </p>
    <h3>Took my number ...</h3>
    <p>It’s getting fucking old. Fuck. To surpass others is fucking tough, if you only do as you are told you don’t have it in you to succeed. </p>
    <h3>.. and waited in line</h3>
    <p>You won’t get good at anything by doing it a lot fucking aimlessly. While having drinks with Tibor Kalman one night, he told me, “When you make something no one hates, no one fucking loves it.” This design is fucking brilliant. Never, never assume that what you have achieved is fucking good enough. Never let your guard down by thinking you’re fucking good enough. Design is all about fucking relationships—the relationship of form and content, the relationship of elements, the relationship of designer and user. Your rapidograph pens are fucking dried up, the x-acto blades in your bag are rusty, </p>
    <h2>Over the lazy dog</h2>
    <p>Must-do is a good fucking master. Design as if your fucking life depended on it. Can we all just agree as the greater design community to stop fucking talking about Comic Sans altogether? It’s getting fucking old. Fuck. To surpass others is fucking tough, if you only do as you are told you don’t have it in you to succeed. </p>
    <h3>Examples</h3>
    <h4>List</h4>
    <ul>
    	<li>You won’t get good at anything by doing it</li>
    	<li>a lot fucking aimlessly. </li>
    	<li>While having drinks with Tibor Kalman one night</li>
    </ul>
    <h4>Ordered List</h4>
    <ol>
    	<li>he told me, “When you make something no one hates, no one fucking loves it.” 
    	<li>This design is fucking brilliant. 
    	<li>Never, never assume that what you have achieved is fucking good enough. 
    </ol>

    <p>Never let your guard down by thinking you’re fucking good enough. Design is all about fucking relationships—the relationship of form and content, the relationship of elements, the relationship of designer and user. Your rapidograph pens are fucking dried up, the x-acto blades in your bag are rusty, </p>

</section>