<nav role="main" class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><div id="logo"><figure class="logo logo--tiny"></figure></div> Styleguide</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="index.php">Home </a></li>
            <?php
                foreach ($Styleguide->getSources() as $source) {
                    echo '<li class="dropdown"><a href="#"  data-toggle="dropdown">'. $source->getName() .'<span class="caret"></span></a><ul class="dropdown-menu">';
                    foreach ($source->getParser()->getTopLevelSections() as $topLevelSection) {
                        echo '<li>
                            <a href="index.php?ref='.$topLevelSection->getReference().'&src='.$source->getKey().'" title="'.$topLevelSection->getTitle().'">' .
                                $topLevelSection->getDescriptionTitle() .
                            '</a>' .
                        '</li>';
                    }
                    echo '</ul></li>';
                }
            ?>
            </ul>
        </div>
    </div>
</nav>
