<div class="styleguidePreviewRoot">
	<div class="styleguide__preview">
		<div class="styleguide_preview_element">
		    <?php echo $vars['section']->getMarkupNormal(); ?>
		</div>
	<?php foreach ($vars['section']->getModifiers() as $modifier) { ?>
	    <div class="styleguide__preview__element styleguide__element--modifier <?php ($modifier->isExtender()) ? 'styleguide__element--extender' : ''; ?>">
	        <span class="styleguide__preview__element__modifier-label <?php echo ($modifier->isExtender()) ? 'styleguide__element__modifier-label--extender' : ''; ?>"><?php echo $modifier->getName(); ?></span>
	       	<?php echo $modifier->getExampleHtml(); ?>
	    </div>
	<?php } ?>
	</div>
</div>