<main>
<article>

<h1><?php echo $vars['section']->getDescriptionTitle() ?></h1>
<p class="lead"><?php echo $vars['section']->getDescriptionText(); ?></p>
<?php
    foreach ($Styleguide->getSource()->getParser()->getSectionChildren($Styleguide->getRef()) as $section) {
        $Styleguide->displayTemplate('Block', array('section' => $section, 'styleguide' => $Styleguide));
    }
?>
</article>
</main>