<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Styleguide Preview</title>
    <?php 

    foreach ($Styleguide->getSource()->getCSSResources() as $resource) {
    	echo '<link rel="stylesheet" type="text/css" href="'.$resource.'" />';
    }

    foreach ($Styleguide->getSource()->getJSResources() as $resource) {
    	echo '<script src="'.$resource.'"></script>';
    }

    ?>
    
    <link rel="stylesheet" href="css/preview.css" />

</head>
<body>

	<?php $Styleguide->displayTemplate('Preview', $vars); ?>

</body>
</html> 